version: "3"

services:
  node:
    restart: unless-stopped
    container_name: node
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www:delegated
      - /var/www/node_modules
    depends_on:
      - postgres
    networks:
      - network-bridge


  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: postgres
    build:
      context: ./compose/docker/postgres
    ports:
      - "5432:5432"
    env_file: ./compose/env/db.env
    volumes:
      - postgresqldata:/var/lib/postgresql
    networks:
      - network-bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    secrets:
      - db_password

volumes:
  postgresqldata:

networks:
  network-bridge:
    driver: bridge

# docker-compose up -d